owner: danieledigregorio
repo: status

sites:
  - name: Daniele Di Gregorio
    url: https://www.danieledigregorio.it
  - name: digreg.dev
    url: https://digreg.dev
  - name: CineFX
    url: https://cinefx.danieledigregorio.it

status-website:
  cname: status.digreg.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | digreg.dev
  introTitle: "**Status** | digreg.dev"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
